# Generated by Django 4.2 on 2023-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.PositiveIntegerField(null=True, verbose_name='Density'),
        ),
    ]
