# Generated by Django 4.2 on 2023-05-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Обозначение')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ('designation',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Обозначение')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='archive.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('designation',),
            },
        ),
        migrations.CreateModel(
            name='AssemblyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.assembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.part')),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='parts',
            field=models.ManyToManyField(blank=True, through='archive.AssemblyPart', to='archive.part', verbose_name='Детали'),
        ),
    ]
