# Generated by Django 4.2 on 2023-05-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'ordering': ('designation',), 'verbose_name': 'Сборка', 'verbose_name_plural': 'Сборки'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('designation',), 'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
    ]
