# Generated by Django 4.2 on 2023-05-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_assemblypart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'ordering': ('designation',), 'verbose_name': 'Assembly', 'verbose_name_plural': 'Assemblies'},
        ),
        migrations.AlterModelOptions(
            name='assemblypart',
            options={'verbose_name': 'Part in assembly', 'verbose_name_plural': 'Parts in assembly'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('designation',), 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterField(
            model_name='assembly',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='designation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='parts',
            field=models.ManyToManyField(blank=True, through='archive.AssemblyPart', to='archive.part', verbose_name='Parts'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of change'),
        ),
        migrations.AlterField(
            model_name='assemblypart',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.assembly', verbose_name='Assembly'),
        ),
        migrations.AlterField(
            model_name='assemblypart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.part', verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='assemblypart',
            name='part_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of change'),
        ),
        migrations.AlterField(
            model_name='part',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='part',
            name='designation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='part',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='archive.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of change'),
        ),
    ]
