# Generated by Django 4.2 on 2023-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Density'),
        ),
    ]
