name: CI

on: [push, pull_request]

jobs:
  tests:

    name: Run tests and flake8
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install - r lesson_11/req.txt

      - name: Run tests
        run: |
          python lesson_11/manage.py test materials parts assemblies

      - name: Run linter
        run: |
          flake8 lesson_11/